WebApiTestApplication/Controllers/DefaultPageController.cs
using System.Web.Http;
using System.Web.Mvc;

namespace WebApiTestApplication.Controllers
{
    public class DefaultPageController : Controller
    {
        [System.Web.Mvc.HttpGet]
        public ActionResult Index(string from, string to)
        {
            if (string.IsNullOrEmpty(from) || string.IsNullOrEmpty(to))
            {
                return View();
            }
            ViewBag.Title = "Default page";
            return View();
        }
    }
}

WebApiTestApplication/Controllers/WordController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using WebApiTestApplication.Exceptions;
using WebApiTestApplication.Filters;
using WebApiTestApplication.Services;

namespace WebApiTestApplication.Controllers
{
    [WordsRangeExceptionFilter]
    public class WordController : ApiController
    {
        private readonly IWordsRangeService _wordsRangeService;

        public WordController(IWordsRangeService wordsRangeService)
        {
            _wordsRangeService = wordsRangeService;
        }

        public async Task<IEnumerable<string>> Get()
        {
            return await Task.FromResult(new string[] {});
        }

        // GET api/values

        public IEnumerable<string> Get(string from, string to)
        {
            if (string.IsNullOrEmpty(from) || string.IsNullOrEmpty(to))
            {
                throw new InvalidWordRangeArgumentException("Invalid word range arguments 'from' or 'to'.");
            }
            return _wordsRangeService.GetRange(from, to);
        }
    }
}

WebApiTestApplication/Views/DefaultPage/Index.cshtml
<script type="text/template" id="rangeTemplate">
    <div class="outer">
        <div class="inner">
            F
        </div>
        <div class="content"></div>
        <div class="show-all">
            <a href="javascript:void(0)">show all...</a>
        </div>
    </div>
</script>



<div class="jumbotron nopadding">
    <p class="lead">Please type url with parameters in the address bar.</p>
    <p class="lead">Example: http://localhost:30183/DefaultPage?from=aali&to=sharai </p>
</div>
<div class="row">
    <div class="" style="clear: both" id="wordsContainer">
    </div>
</div>

WebApiTestApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Words range web api test", "Index", "DefaultPage", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Evgeniy Boklag test task</p>
    </footer>
</div>

    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Modal title</h4>
                </div>
                <div class="modal-body">
                    <p>One fine body…</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->



@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/application")
    @RenderSection("scripts", required: false)
</body>
</html>